var country_arr = new Array("BAGERHAT", "BANDARBAN", "BARGUNA", "BARISHAL", "BHOLA", "BOGURA"," BRAHMANBARIA", "CHANDPUR","CHAPAINAWABGANJ", "CHATTOGRAM", "CHUADANGA","COX`S BAZAR", "CUMILLA", "DHAKA", "DINAJPUR", "FARIDPUR", "FENI", "GAIBANDHA", "GAZIPUR", "GOPALGANJ", "HABIGANJ","JAMALPUR", "JASHORE", "JHALAKATI", "JHENAIDAH", "JOYPURHAT","KHAGRACHARI","KHULNA", "KISHOREGANJ", "KURIGRAM", "KUSHTIA", "LAKSHMIPUR", "LALMONIRHAT", "MADARIPUR", "MAGURA", "MANIKGANJ", "MEHERPUR", "MOULVIBAZAR", "MUNSHIGANJ", "MYMENSINGH", "NAOGAON", "NARAIL", "NARAYANGANJ","NARSINGDI", "NATORE", "NETROKONA", "NILPHAMARI", "NOAKHALI", "PABNA", "PANCHAGARH", "PATUAKHALI", "PIROJPUR", "RAJBARI","RAJSHAHI", "RANGAMATI", "RANGPUR","SATKHIRA", "SHARIATPUR", "SHERPUR","SIRAJGANJ", "SUNAMGANJ", "SYLHET", "TANGAIL", "THAKURGAON");



var s_a = new Array();
s_a[1]="BAGERHAT SADAR   || CHITALMARI   || FAKIRHAT   || KACHUA   || MOLLAHAT   || MONGLA   || MORRELGANJ   || RAMPAL   ||SARANKHOLA";
s_a[2]=" ALIKADAM   || BANDARBAN SADAR   || LAMA   || NAIKHONGCHHARI   || ROWANGCHARI   || RUMA   || THANCHI   || ";
s_a[3]=" AMTOLI   || BAMNA   || BARGUNA   || BETAGI   || PATHARGHATA   || TALTOLI";
s_a[4]=" AGAILJHARA   || AIRPORT   || BABUGANJ   || BAKERGANJ   || BANARIPARA   || BANDAR   || GOURNADI   || HIZLA   || KAWNIA   || KAZIRHAT   || KOTWALI MODEL   || MEHENDIGANJ   || MULADI   || WAZIRPUR   || ";
s_a[5]=" BHOLA SADAR   || BURHANUDDIN   || CHARFASSON   || DAKSHIN AICHA   || DAULATKHAN   || DULARHAT   || LALMOHAN   || MANPURA   || SOSHIVUSION   || TAZUMUDDIN";
s_a[6]=" ADAMDIGHI   || BOGURA SADAR   || DHUNAT   || DHUPCHANCHIA   || GABTALI   || KAHALOO   || NANDIGRAM   || SARIAKANDI   || SHAJAHANPUR   || SHERPUR   || SHIBGANJ   || SONATOLA";
s_a[7]=" AKHAURA   || ASHUGANJ   || BANCHARAMPUR   || BIJOYNAGAR   || BRAHMANBARIA SADAR   || KASBA   || NABINAGAR   || NASIRNAGAR   || SARAIL";
s_a[8]=" CHANDPUR SADAR  ||	FARIDGANJ  ||	HAIMCHAR  ||	HAZIGANJ  ||	MATLAB DAKSHIN  ||	MATLAB UTTAR  ||	SHAHRASTI";
s_a[9]=" BHOLAHAT  ||	GOMOSTAPUR  ||	NACHOL  ||	CHAPAINAWABGANJ SADAR  ||	SHIBGANJ";
s_a[10]=" AKBARSHAH  ||	ANWARA  ||	BAKALIA  ||	BANDAR  ||	BANSHKHALI  ||	BAYEZID BOSTAMI  ||	BHUJPUR  ||	BOALKHALI  ||	CHANDANAISH  ||	CHANDGAON  ||	CHAWKBAZAR  ||	DOUBLE MOORING  ||	EPZ  ||	FATIKCHHARI  ||	HALISHAHAR  ||	HATHAZARI  ||	JORARGANJ  ||	KARNAPHULI  ||	KHULSHI  ||	KOTOWALI  ||	LOHAGARA  ||	MIRSHARAI  ||	PAHARTOLI  ||	PANCHLAISH  ||	PATENGA  ||	PATIYA  ||	RANGUNIA  ||	RAOZAN  ||	SADARGHAT  ||	SANDWIP  ||	SATKANIA  ||	SITAKUNDA";
s_a[11]=" ALAMDANGA  ||	CHUADANGA SADAR  ||	DAMURHUDA  ||	DARSHANA  ||	JIBANNAGAR";
s_a[12]=" CHAKARIA  ||	COX`S BAZAR  ||	EIDGAON  ||	KUTUBDIA  ||	MAHESHKHALI  ||	PEKUA  ||	RAMU  ||	TEKNAF  ||	UKHIA";
s_a[13]=" BANGORA BAZAR  ||	BARURA  ||	BRAHMANPARA  ||	BURICHONG  ||	CHANDINA  ||	CHAUDDAGRAM  ||	DAUDKANDI  ||	DEBIDWAR  ||	HOMNA  ||	KOTWALI MODEL  ||	LAKSAM  ||	LALMAI  ||	MANOHARGANJ  ||	MEGHNA  ||	MURADNAGAR  ||	NANGALKOT  ||	SADAR DAKSHIN  ||	TITAS";
s_a[14]=" ADABOR  ||	AIRPORT  ||	ASHULIA  ||	BADDA  ||	BANANI  ||	BANGSHAL  ||	CANTONMENT  ||	CHAWKBAZAR  ||	DAKSHINKHAN  ||	DARUS SALAM  ||	DEMRA  ||	DHAMRAI  ||	DHANMONDI  ||	DOHAR  ||	GENDARIA  ||	GULSHAN  ||	HATIRJHEEL  ||	HAZARIBAGH  ||	JATRABARI  ||	KADOMTOLI  ||	KAFRUL  ||	KALABAGAN  ||	KAMRANGIRCHAR  ||	KERANIGANJ  ||	KHILGAON  ||	KHILKHET  ||	KOTWALI  ||	LALBAGH  ||	MIRPUR  ||	MOHAMMADPUR  ||	MOTIJHEEL  ||	MUGDA  ||	NAWABGONJ  ||	NEW MARKET  ||	PALLABI  ||	PALTAN  ||	RAMNA  ||	RAMPURA  ||	RUPNAGAR  ||	SABUJBAGH  ||	SAVAR  ||	SHAH ALI  ||	SHAHBAGH  ||	SHAHJAHANPUR  ||	SHAMPUR  ||	SHER-E-BANGLA NAGAR  ||	SOUTH KERANIGANJ  ||	SUTRAPUR  ||	TEJGAON  ||	TEJGAON INDUSTRIAL AREA  ||	TURAG  ||	UTTARA EAST  ||	UTTARA WEST  ||	UTTARKHAN  ||	VASHANTEK  ||	VATARA  ||	WARI";
s_a[15]=" BIRAL  ||	BIRAMPUR  ||	BIRGANJ  ||	BOCHAGANJ  ||	CHIRIRBANDAR  ||	GHORAGHAT  ||	HAKIMPUR  ||	KAHAROLE  ||	KHANSAMA  ||	KOTWALI  ||	NAWABGANJ  ||	PARBATIPUR  ||	PHULBARI";
s_a[16]=" ALFADANGA  ||	BHANGA  ||	BOALMARI  ||	CHAR BHADRASAN  ||	KOTWALI  ||	MADHUKHALI  ||	NAGARKANDA  ||	SADARPUR  ||	SALTHA";
s_a[17]=" CHHAGALNAIYA  ||	DAGONBHUIYAN  ||	FENI SADAR  ||	FULGAZI  ||	PARSHURAM  ||	SONAGAZI";
s_a[18]=" FULCHHARI  ||	GAIBANDHA SADAR  ||	GOBINDAGANJ  ||	PALASHBARI  ||	SADULLAPUR  ||	SHAGHATA  ||	SUNDARGANJ";
s_a[19]=" BASON  ||	GACHA  ||	GAZIPUR SADAR  ||	JOYDEBPUR  ||	KALIAKAIR  ||	KALIGANJ  ||	KAPASIA  ||	KASIMPUR  ||	KONABARI  ||	PUBAIL  ||	SREEPUR  ||	TONGI EAST  ||	TONGI WEST";
s_a[20]=" GOPALGANJ  ||	KASHIANI  ||	KOTALIPARA  ||	MUKSUDPUR  ||	TUNGIPARA";
s_a[21]=" AJMIRIGANJ  ||	BAHUBAL  ||	BANIYACHONG  ||	CHUNARUGHAT  ||	HABIGANJ  ||	LAKHAI  ||	MADHABPUR  ||	NABIGANJ  ||	SHAESTAGONJ";
s_a[22]=" BAKSHIGONJ  ||	DEWANGANJ  ||	ISLAMPUR  ||	JAMALPUR SADAR  ||	MADARGANJ  ||	MELANDOHO  ||	SARISHABARI";
s_a[23]=" ABHAYNAGAR  ||	BAGHERPARA  ||	BENAPOLE PORT  ||	CHAUGACHHA  ||	JHIKARGACHHA  ||	KESHABPUR  ||	KOTWALI  ||	MANIRAMPUR  ||	SHARSHA";
s_a[24]=" JHALOKATI  ||	KATHALIA  ||	NALCHITY  ||	RAJAPUR";
s_a[25]=" HARINAKUNDA  ||	JHENAIDAH  ||	KALIGANJ  ||	KOTCHANDPUR  ||	MAHESHPUR  ||	SHAILKUPA";
s_a[26]=" AKKELPUR  ||	JOYPURHAT  ||	KALAI  ||	KHETLAL  ||	PANCHBIBI";
s_a[27]=" DIGHINALA  ||	GUIMARA  ||	KHAGRACHARI  ||	LAKSHMICHARI  ||	MAHALCHARI  ||	MANIKCHARI  ||	MATIRANGA  ||	PANCHHARI  ||	RAMGARH";
s_a[28]=" ARONGHATA  ||	BATIAGHATA  ||	DACOPE  ||	DAULATPUR  ||	DIGHOLIA  ||	DUMURIA  ||	HORINTANA  ||	KHALISHPUR  ||	KHAN JAHAN ALI  ||	KHULNA SADAR  ||	KOYRA  ||	LABANCHORA  ||	PAIKGACHA  ||	PHULTALA  ||	RUPSHA  ||	SONADANGA MODEL  ||	TEROKHADA";
s_a[29]=" AUSTAGRAM  ||	BAJITPUR  ||	BHAIRAB  ||	HOSSAINPUR  ||	ITNA  ||	KARIMGANJ  ||	KATIADI  ||	KISHOREGANJ SADAR  ||	KULIARCHAR  ||	MITHAMAIN  ||	NIKLI  ||	PAKUNDIA  ||	TARAIL";
s_a[30]=" BHURUNGAMARI  ||	CHAR RAJIBPUR  ||	CHILMARI  ||	DUSMARA  ||	KACHAKATA  ||	KURIGRAM SADAR  ||	NAGESHWARI  ||	PHULBARI  ||	RAJARHAT  ||	ROWMARI  ||	ULIPUR";
s_a[31]=" BHERAMARA  ||	DAULATPUR  ||	ISLAMIC UNIVERSITY  ||	KHOKSA  ||	KUMARKHALI  ||	KUSHTIA MODEL  ||	MIRPUR";
s_a[32]=" CHANDRAGONJ  ||	KAMALNAGAR  ||	LAKSHMIPUR SADAR  ||	RAIPUR  ||	RAMGANJ  ||	RAMGATI";
s_a[33]=" ADITMARI  ||	HATIBANDHA  ||	KALIGANJ  ||	LALMONIRHAT  ||	PATGRAM";
s_a[34]=" DASHAR  ||	KALKINI  ||	MADARIPUR SADAR  ||	RAJOIR  ||	SHIBCHAR";
s_a[35]=" MAGURA SADAR  ||	MOHAMMADPUR  ||	SHALIKHA  ||	SREEPUR";
s_a[36]=" DAULATPUR  ||	GHIOR  ||	HARIRAMPUR  ||	MANIKGANJ SADAR  ||	SATURIA  ||	SHIBALAYA  ||	SINGAIR";
s_a[37]=" GANGNI  ||	MEHERPUR SADAR  ||	MUJIBNAGAR";
s_a[38]=" BARLEKHA  ||	JURI  ||	KOMOLGANJ  ||	KULAURA  ||	MOULVIBAZAR SADAR  ||	RAJNAGAR  ||	SRIMANGAL";
s_a[39]=" GAZARIA  ||	LOUHAJONG  ||	MUNSHIGANJ  ||	PADMA SETU NORTH  ||	SIRAJDIKHAN  ||	SREENAGAR  ||	TONGIBARI";
s_a[40]=" BHALUKA  ||	DHOBAURA  ||	FULBARIA  ||	GAFORGAON  ||	GOURIPUR  ||	HALUAGHAT  ||	ISHWARGANJ  ||	KOTWALI  ||	MUKTAGACHA  ||	NANDAIL  ||	PAGLA  ||	PHULPUR  ||	TARAKANDA  ||	TRISHAL";
s_a[41]=" ATRAI  ||	BADALGACHHI  ||	DHAMOIRHAT  ||	MAHADEBPUR  ||	MANDA  ||	NAOGAON SADAR  ||	NIAMATPUR  ||	PATNITALA  ||	PORSHA  ||	RANINAGAR  ||	SAPAHAR";
s_a[42]=" KALIA  ||	LOHAGARA  ||	NARAGATI  ||	NARAIL SADAR";
s_a[43]=" ARAIHAZAR  ||	BANDAR  ||	FATULLAH  ||	NARAYANGANJ SADAR  ||	RUPGANJ  ||	SIDDHIRGANJ  ||	SONARGAON";
s_a[44]=" BELABO  ||	MADHABDI  ||	MONOHARDI  ||	NARSINGDI SADAR  ||	PALASH  ||	RAIPURA  ||	SHIBPUR";
s_a[45]=" BAGATIPARA  ||	BARAIGRAM  ||	GURUDASPUR  ||	LALPUR  ||	NALDANGA  ||	NATORE  ||	SINGRA";
s_a[46]=" ATPARA  ||	BARHATTA  ||	DURGAPUR  ||	KALMAKANDA  ||	KENDUA  ||	KHALIAJURI  ||	MODON  ||	MOHANGANJ  ||	NETROKONA SADAR   ||	PURBODHALA";
s_a[47]=" DIMLA  ||	DOMAR  ||	JALDHAKA  ||	KISHOREGANJ  ||	NILPHAMARI SADAR  ||	SAIDPUR";
s_a[48]=" BEGUMGANJ  ||	BHASAN CHAR  ||	CHARJABBAR  ||	CHATKHIL  ||	COMPANIGONJ  ||	HATIYA  ||	KABIRHAT  ||	SENBAGH  ||	SONAIMURI  ||	SUDHARAM";
s_a[49]=" AMINPUR  ||	ATAIKULA  ||	ATGHARIA  ||	BERA  ||	BHANGURA  ||	CHATMOHAR  ||	FARIDPUR  ||	ISHWARDI  ||	PABNA SADAR  ||	SANTHIA  ||	SUJANAGAR";
s_a[50]=" ATWARI  ||	BODA  ||	DEBIGANJ  ||	PANCHAGARH SADAR  ||	TETULIA";
s_a[51]=" BAUPHAL  ||	DASHMINA  ||	DUMKI  ||	GALACHIPA  ||	KALAPARA  ||	MIRZAGANJ  ||	MOHIPUR  ||	PATUAKHALI SADAR  ||	RANGABALI";
s_a[52]=" BHANDARIA  ||	INDURKANI  ||	KAWKHALI  ||	MATHBARIA  ||	NAZIRPUR  ||	NESARABAD  ||	PIROJPUR SADAR";
s_a[53]=" BALIAKANDI  ||	GOALANDA GHAT  ||	KALUKHALI  ||	PANGSHA  ||	RAJBARI";
s_a[54]=" AIRPORT  ||	BAGHA  ||	BAGMARA  ||	BILPUKUR  ||	BOALIA MODEL  ||	CHANDRIMA  ||	CHARGHAT  ||	DAMKURA  ||	DURGAPUR  ||	GODAGARI  ||	KASHIADANGA  ||	KATAKHALI  ||	KORNAHAR  ||	MOHANPUR  ||	MOTIHAR  ||	PABA  ||	PUTHIA  ||	RAJPARA  ||	SHAH MAKHDUM  ||	TANOR";
s_a[55]=" BAGHAICHHARI  ||	BARKAL  ||	BELAICHHARI  ||	CHANDROGHONA  ||	JURAICHHARI  ||	KAPTAI	  ||KAWKHALI  ||	KOTWALI  ||	LANGADU  ||	NANIARCHAR  ||	RAJASTHALI  ||	SAJEK";
s_a[56]=" BADARGANJ  ||	GANGACHARA  ||	HARAGACH  ||	HAZIRHAT  ||	KAUNIA  ||	KOTWALI METRO  ||	MAHIGONJ  ||	MITHA PUKUR  ||	PIRGACHHA  ||	PIRGANJ  ||	PORSHURAM  ||	RANGPUR SADAR  ||	TAJHAT  ||	TARAGANJ";
s_a[57]=" ASHASHUNI  ||	DEBHATA  ||	KALAROA  ||	KALIGANJ  ||	PATKELGHATA  ||	SATKHIRA SADAR  ||	SHYAMNAGAR  ||	TALA";
s_a[58]=" BHEDARGANJ  ||	DAMUDYA  ||	GOSAIRHAT  ||	JAJIRA  ||	NARIA  ||	PADMA SETU SOUTH  ||	PALONG MODEL  ||	SHAKHIPUR";
s_a[59]=" JHINAIGATI  ||	NAKLA  ||	NALITABARI  ||	SHERPUR  ||	SRIBARDI";
s_a[60]=" BANGABANDHU SETU WEST  ||	BELKUCHI  ||	CHOWHALI  ||	ENAYETPUR  ||	KAMARKHANDA  ||	KAZIPUR  ||	RAIGONJ  ||	SALANGA  ||	SHAHZADPUR  ||	SIRAJGANJ  ||	TARASH  ||	ULLAPARA MODEL";
s_a[61]=" BISHWAMBARPUR  ||	CHHATAK  ||	DAKSHIN SUNAMGANJ  ||	DERAI  ||	DHARAMPASHA  ||	DOWARABAZAR  ||	JAGANNATHPUR  ||	JAMALGANJ  ||	MADHANAGAR  ||	SULLAH  ||	SUNAMGANJ SADAR  ||	TAHIRPUR";
s_a[62]=" AIRPORT  ||	BALAGANJ  ||	BEANIBAZAR  ||	BISHWANATH  ||	COMPANYGONJ  ||	FENCHUGONJ  ||	GOLAPGONJ  ||	GOWAINGHAT  ||	JAINTAPUR  ||	JALALABAD  ||	KANAIGHAT  ||	KOTWALI  ||	MOGLABAZAR  ||	OSMANINAGAR  ||	SHAHPORAN  ||	SOUTH SURMA  ||	ZOKIGANJ";
s_a[63]=" BANGABANDHU SETU EAST  ||	BASAIL  ||	BHUAPUR  ||	DELDUAR  ||	DHANBARI  ||	GHATAIL  ||	GOPALPUR  ||	KALIHATI  ||	MADHUPUR  ||	MIRZAPUR  ||	NAGARPUR  ||	SAKHIPUR  ||	TANGAIL SADAR";
s_a[64]=" BALIADANGI  ||	HARIPUR  ||	PIRGANJ  ||	RANISANKAIL  ||	RUHIA  ||	THAKURGAON SADAR";








function print_country(country_id){
	// given the id of the <select> tag as function argument, it inserts <option> tags
	var option_str = document.getElementById(country_id);
	option_str.length=0;
	option_str.options[0] = new Option('Select Country','');
	option_str.selectedIndex = 0;
	for (var i=0; i<country_arr.length; i++) {
		option_str.options[option_str.length] = new Option(country_arr[i],country_arr[i]);
	}
}



function print_state(state_id, state_index){
    var option_str = document.getElementById(state_id);
    option_str.length=0;    // Fixed by Julian Woods
    option_str.options[0] = new Option('Select state','');
    option_str.selectedIndex = 0;
      state_arr = s_a[state_index].split("  ||");
    for (var i=0; i<state_arr.length; i++) {
        option_str.options[option_str.length] = new Option(state_arr[i],state_arr[i]);
    }
}





$(document).ready(function(){
 
	// Initialize select2
	$("#country1").select2();
	$("#state1").select2();
   
	// Read selected option
	$('#but_read').click(function(){
		var username = $('#country1 option:selected').text();
		var userid = $('#country1').val();
   
		$('#result').html ("id : " + userid + ", name : " + username);
   
	});
   });

